#!/usr/bin/env bash
# Configures Nginx to send the X-Served-By HTTP response header.

apt-get -y update
apt-get -y install nginx

if ! grep -q "X-Served-By" /etc/nginx/sites-available/default; then
    sed -i '/location \/ {/a \        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
fi

systemctl restart nginx
