#!/usr/bin/env bash
# This script installs Nginx, and serves a page containing "Holberton School for the win!"
apt-get update
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html

service nginx start
